# Development Dockerfile for Notification Service
FROM node:18-alpine

WORKDIR /app

# Install dependencies for development
# RUN apk add --no-cache git

# Copy package files
# COPY package*.json ./

# Copy source code
COPY . .

# Install all dependencies (including dev dependencies)
RUN npm install

# Expose port
EXPOSE 3004

# Start in development mode with hot reload
CMD ["npm", "run", "start:dev"]
# CMD ["tail", "-f" , "/dev/null"]
